nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: []
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:

        '^/api/v1/':
            allow_origin: ['^http://ec2-54-197-127-233.compute-1.amazonaws.com']
            allow_headers: ['X-Custom-Auth']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600

        '^/': null
